Create new App
Skitus/gitHubSearcherV2 pull request #1
Opened 2021-10-17 10:37 UTC by Skitus

2021-10-18 14:11 UTC, dev1B requested changes

2021-10-18 14:11 UTC, dev1B commented on .idea/github-searcher-master.iml
> +<module type="WEB_MODULE" version="4">
gitignore

2021-10-18 14:11 UTC, dev1B commented on src/components/Detail/Detail.tsx
>          dispatch(fetchGetUser(userName));
Можливо ти інформацію про юзера можеш зі стейту потягнути

2021-10-18 14:11 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +        debounce(changeHandler, 1000)
Дуже велика затримка

2021-10-18 14:11 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +                status ?
Що таке статус?

2021-10-18 14:11 UTC, dev1B commented on src/dal/http.ts
> +        private URL: string = 'https://api.github.com/',
Чому це в конструкторі?

Якщо я зроблю  const http = new Http('google.com');
http.getAllUsers("artur") 
Що буде ?

2021-10-22 22:22 UTC, dev1B requested changes

2021-10-22 22:22 UTC, dev1B commented on .eslintrc.json
> +        /*        "eslint:recommended",*/
?

2021-10-22 22:22 UTC, dev1B commented on .gitignore
> +/.idea
?

2021-10-22 22:22 UTC, dev1B commented on .idea/github-searcher-master.iml
> +<module type="WEB_MODULE" version="4">
GREAT JOB!


gitignore 2

2021-10-22 22:22 UTC, dev1B commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/.idea/github-searcher-master.iml" filepath="$PROJECT_DIR$/.idea/github-searcher-master.iml" />
gitignore 3

2021-10-22 22:22 UTC, dev1B commented on .idea/vcs.xml
> +    <mapping directory="$PROJECT_DIR$" vcs="Git" />
gitignore 4

2021-10-22 22:22 UTC, dev1B commented on .idea/workspace.xml
> +    <option name="HIGHLIGHT_CONFLICTS" value="true" />
gitignore 5

2021-10-22 22:22 UTC, dev1B commented on src/components/Home/Home.tsx
> +          usersRequest.isLoading ? <Spin size="large" /> : <DetailRoute />
any comment ?

2021-10-22 22:22 UTC, dev1B commented on src/components/User/User.tsx
> +  <>
remove ?

2021-10-22 22:22 UTC, dev1B commented on src/dal/http.ts
> +    private URL = 'https://api.github.com/';
BASE_URL => baseUrl ( зазвичай так роблять)
 і можна добавити readonly

2021-10-22 22:22 UTC, dev1B commented on src/store/strore.ts
> +    usersRepos: usersRepoReducer,
?

2021-10-22 22:22 UTC, dev1B commented on src/store/usersRepos/usersRepo.slice.ts
> +    console.log('res', res);
?

2021-10-22 22:22 UTC, dev1B commented on src/types/User.types.ts
> +export interface IUser {
I

2021-10-25 18:40 UTC, dev1B requested changes

2021-10-25 18:40 UTC, dev1B commented on public/robots.txt
> +UserProfile-agent: *
Шо ти тут робив ?

2021-10-25 18:40 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +  const userRepoRequest = useSelector(userRepoSelector);
userRepo

2021-10-25 18:40 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +  const changeHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
name

2021-11-09 17:56 UTC, OlegDsalo commented on src/App.tsx
> +    <div className="max-length">
bad name

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/Detail/Detail.tsx
> +  const userRepoBlock = React.useRef<HTMLHeadingElement>(null);
?

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/Detail/Detail.tsx
> +    if (repoIsLoading === false) {
!repoIsloading

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/Home/Home.tsx
> +  let total = useSelector(selectUsersTotalCount);
total > totalUsers>usersTotalCount

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/NumberRepos/NumberRepos.tsx
> +    <div key={repo.id} className="blockRepos">
class name left side

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/NumberRepos/NumberRepos.tsx
> +        {' '}
&+nbsp;

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/UserProfileRepos/UserProfileRepos.tsx
> +                {' '}
?

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/UserProfileRepos/UserProfileRepos.tsx
> +                {' '}
?

2021-11-09 17:56 UTC, OlegDsalo commented on src/store/userRepo/userRepo.selector.ts
> +export const selectUsers = (state: any) => state.userRepo;
selectUsers = userRepo ????

2021-11-09 17:56 UTC, OlegDsalo commented on src/store/users/users.selector.ts
> +export const selectUsers = (state: any) => state.users;
2 selectUsers?

2021-11-09 17:56 UTC, OlegDsalo commented on src/components/Pagination/PaginationUsers.tsx
> +      >
all time show last page ????

2021-11-09 17:56 UTC, OlegDsalo commented on src/store/userRepo/userRepo.slice.ts
> +// todo add offset
??

2021-11-09 17:57 UTC, OlegDsalo commented on src/components/NumberRepos/NumberRepos.tsx
> +        {' '}
&nbsp;

2021-11-09 20:07 UTC, dev1B requested changes

2021-11-09 20:07 UTC, dev1B commented on src/App.scss
> +.max-width {
classname

2021-11-09 20:07 UTC, dev1B commented on src/components/Detail/Detail.scss
> +.userRepo-scroll {
.userRepo-scroll - fix name

2021-11-09 20:07 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +  const perPageUserRepo = useSelector(selectUserRepoPerPage);
Дуже багато селекторів... 
Можна менше)
const userRepoReq = useSelector(...);

2021-11-09 20:07 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +  const changeRepoName = (event: React.ChangeEvent<HTMLInputElement>) => {
changeRepoName ?

2021-11-09 20:07 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +      // eslint-disable-next-line prefer-const
?

2021-11-09 20:07 UTC, dev1B commented on src/components/Detail/Detail.tsx
> +      // eslint-disable-next-line prefer-const
const needLoadMore = currentPageUserRepo < pagesCount;


needLoadMore

2021-11-15 13:42 UTC, merged